name: Deploy para a Umbler

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Instala chave SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
      - name: Checkout do branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Commit para Umbler usando git remote
        run: |
          git remote add umbler ${{ secrets.UMBLER_REMOTE }}
          git push umbler main:master -f